#!/bin/bash 
while read -r line; do
	ADDR=$(echo $line | cut -d ',' -f1)
	NAME=$(echo $line | cut -d ',' -f2)
	IP=$(echo $line | cut -d ',' -f3)
	LAST=$(echo $line | cut -d ',' -f4)
	echo -e "$ADDR\t$NAME\t$IP\t$LAST"
done <<< `sudo cat /etc/openvpn/openvpn-status.log | grep 10.8.0`

